### ISSUE TITLE
Issue in spmconfig.js

### ISSUE THREAD

**Issue by HazCod** [sematext/sematext-agent-httpd#1]
```
undefined:9
}
^

SyntaxError: Unexpected token } in JSON at position 201
    at Object.parse (native)
    at exports.parse (/usr/lib/node_modules/sematext-agent-httpd/node_modules/rc/lib/utils.js:15:17)
    at addConfigFile (/usr/lib/node_modules/sematext-agent-httpd/node_modules/rc/index.js:31:20)
    at new module.exports (/usr/lib/node_modules/sematext-agent-httpd/node_modules/rc/index.js:47:20)
    at new SpmConfig (/usr/lib/node_modules/sematext-agent-httpd/node_modules/spm-agent/lib/util/spmconfig.js:41:12)
    at Object.<anonymous> (/usr/lib/node_modules/sematext-agent-httpd/node_modules/spm-agent/lib/util/spmconfig.js:51:18)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)

```

**Comment by megastef** [comment]
This means the configuration file is not valid JSON.

**Comment by HazCod** [comment]
Unfortunately, this is the only thing I see. :/

```
docker run     --name sematext-agent-httpd     --link proxy     -e SPM_TOKEN=xxx     -e "HTTPD_STATUS_URL=http://proxy/_status"     -ti --rm     sematext/sematext-agent-apache
undefined:9
}
^

SyntaxError: Unexpected token } in JSON at position 201
    at Object.parse (native)
    at exports.parse (/usr/lib/node_modules/sematext-agent-httpd/node_modules/rc/lib/utils.js:15:17)
    at addConfigFile (/usr/lib/node_modules/sematext-agent-httpd/node_modules/rc/index.js:31:20)
    at new module.exports (/usr/lib/node_modules/sematext-agent-httpd/node_modules/rc/index.js:47:20)
    at new SpmConfig (/usr/lib/node_modules/sematext-agent-httpd/node_modules/spm-agent/lib/util/spmconfig.js:41:12)
    at Object.<anonymous> (/usr/lib/node_modules/sematext-agent-httpd/node_modules/spm-agent/lib/util/spmconfig.js:51:18)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)

```

**Comment by megastef** [comment]
Must be in https://github.com/sematext/sematext-agent-httpd/blob/master/docker-run.sh - I'll chcek.

**Comment by megastef** [comment]
This should do the trick https://github.com/sematext/sematext-agent-httpd/commit/0d76766486cd9b756f9c2568f40b3149241bf433

**Comment by HazCod** [comment]
This fixed it, thank you @megastef ! Any reason why this is not an (automated) build on docker hub?

**Comment by megastef** [comment]
@HazCod did the change work for you, after building the docker image from the latest github commit?

**Comment by megastef** [comment]
@HazCod we are planning to add it to Docker Hub, but it was not ready (yet) :)
